#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-bitops
Version  : 1.0.6
Release  : 51
URL      : http://cran.r-project.org/src/contrib/bitops_1.0-6.tar.gz
Source0  : http://cran.r-project.org/src/contrib/bitops_1.0-6.tar.gz
Summary  : Bitwise Operations
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-bitops-lib
BuildRequires : clr-R-helpers

%description


%package lib
Summary: lib components for the R-bitops package.
Group: Libraries

%description lib
lib components for the R-bitops package.


%prep
%setup -q -c -n bitops

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523291645

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1523291645
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bitops
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bitops
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bitops
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library bitops|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bitops/DESCRIPTION
/usr/lib64/R/library/bitops/INDEX
/usr/lib64/R/library/bitops/Meta/Rd.rds
/usr/lib64/R/library/bitops/Meta/features.rds
/usr/lib64/R/library/bitops/Meta/hsearch.rds
/usr/lib64/R/library/bitops/Meta/links.rds
/usr/lib64/R/library/bitops/Meta/nsInfo.rds
/usr/lib64/R/library/bitops/Meta/package.rds
/usr/lib64/R/library/bitops/NAMESPACE
/usr/lib64/R/library/bitops/R/bitops
/usr/lib64/R/library/bitops/R/bitops.rdb
/usr/lib64/R/library/bitops/R/bitops.rdx
/usr/lib64/R/library/bitops/help/AnIndex
/usr/lib64/R/library/bitops/help/aliases.rds
/usr/lib64/R/library/bitops/help/bitops.rdb
/usr/lib64/R/library/bitops/help/bitops.rdx
/usr/lib64/R/library/bitops/help/paths.rds
/usr/lib64/R/library/bitops/html/00Index.html
/usr/lib64/R/library/bitops/html/R.css
/usr/lib64/R/library/bitops/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/bitops/libs/bitops.so
/usr/lib64/R/library/bitops/libs/bitops.so.avx2
/usr/lib64/R/library/bitops/libs/bitops.so.avx512
